[core]
workers = 30


[ShellConfig]
preamble_path = "baselines_tasks/hcc_preamble.sh"
tmp_path_prefix = "/work/scott/equint/tmp"
keep_tmp_files = true


[SlurmConfig]
jobname = "baseline-luigi"
runmode = "runmode_hpc"
group_name = "scott"
partition = "scott,gpu"
cores = 1
mem=16000
time = "3-00:00:00"
threads = 1
gres="gpu:1"

[EvalTask]
base_path = '/work/scott/equint/baselines/'

[TrainTask]
base_path = '/work/scott/equint/baselines/'
