[core]
workers = 10


[ShellConfig]
preamble_path = "unl_luigi/tasks/crane_preamble.sh"
tmp_path_prefix = "/work/{group_name}/{user_name}/tmp/"
keep_tmp_files = false


[SlurmConfig]
jobname = "luigi-job"
runmode = "runmode_hpc"
group_name = "{group_name}"
partition = "batch"
cores = 1
time = "7200"
threads = 1
