[StardustConfig]
stardust_path = "/work/choueiry/ihowell/stampede/nonogram/"


[BlackholeConfig]
blackhole_app = "/work/choueiry/ihowell/binaries/BlackholeApp"
blackhole_path = "/work/choueiry/ihowell/blackhole/nonogram/"


[BlackholeWebConfig]
blackhole_web_path = "/work/choueiry/ihowell/blackhole_web/"


[core]
workers = 900


[ShellConfig]
preamble_path = "unl_luigi/tasks/crane_preamble.sh"
tmp_path_prefix = "/work/{group_name}/{user_name}/tmp/"
keep_tmp_files = false


[SlurmConfig]
jobname = "luigi-job"
runmode = "runmode_hpc"
group_name = "{group_name}"
partition = "batch"
cores = 1
threads = 1
