[core]
workers = 900


[ShellConfig]
preamble_path = "unl_luigi/tasks/crane_preamble.sh"
tmp_path_prefix = "/work/{group_name}/{user_name}/tmp/"
keep_tmp_files = false


[SlurmConfig]
log_dir = "/Users/ihowell/"
group_name = "{group_name}"
partition = "batch"
jobname = "gaps-job"
