[StardustConfig]
stardust_path = "/Users/ihowell/Data/luigi_test_stardust/"


[BlackholeConfig]
blackhole_app = "/Users/ihowell/Projects/blackhole/build/BlackholeApp"
blackhole_path = "/Users/ihowell/Data/luigi_test_blackhole/"


[BlackholeWebConfig]
blackhole_web_path = "/Users/ihowell/Data/luigi_test_blackhole_web/"

[core]
workers = 3


[SlurmConfig]
jobname = "luigi-job"
runmode = "runmode_local"
group_name = "{group_name}"
partition = "batch"
cores = 1
time = "7200"
threads = 1


[ShellConfig]
tmp_path_prefix = "./"
keep_tmp_files = false
