[StardustConfig]
stardust_path = "/mnt/hdd/ihowell/stampede/nonogram/"


[BlackholeConfig]
blackhole_app = "/home/ihowell/blackhole/build/BlackholeApp"
blackhole_path = "/mnt/hdd/ihowell/blackhole/nonogram/"


[BlackholeWebConfig]
blackhole_web_path = "/mnt/hdd/ihowell/blackhole_web/"


[core]
workers = 30


[ShellConfig]
tmp_path_prefix = "/mnt/hdd/ihowell/blackhole/tmp/"
keep_tmp_files = false


[SlurmConfig]
jobname = "luigi-job"
runmode = "runmode_local"
group_name = "{group_name}"
partition = "batch"
cores = 1
time = "7200"
threads = 1
